# -*- coding: utf-8 -*-
"""PCD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIKQ5KQyDuM_VTadTFqDMkfCSvfDWlZW
"""

import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns

"""## 1. Data Loading"""

# Load the dataset
try:
    df = pd.read_csv('/content/Dataset_CIC/Friday-WorkingHours-Morning.pcap_ISCX.csv', encoding='latin1')
    print("Dataset loaded successfully.")
    print(f"Shape of the dataset: {df.shape}")
    print("First 5 rows of the dataset:")
    print(df.head())
except FileNotFoundError:
    print("Error: Dataset file not found. Please ensure the path is correct.")
except Exception as e:
    print(f"An error occurred while loading the dataset: {e}")

"""## 2. Exploratory Data Analysis (EDA)

### 2.1. Basic Information
"""

print("Dataset Info:")
df.info()

"""### 2.2. Descriptive Statistics"""

print("Descriptive Statistics:")
print(df.describe())

"""### 2.3. Missing Values"""

print("Missing Values (Count):")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nMissing Values (Percentage):")
print(df.isnull().sum()[df.isnull().sum() > 0] / len(df) * 100)

"""### 2.4. Duplicate Rows"""

print("Number of duplicate rows:", df.duplicated().sum())

"""## 3. Data Preprocessing

### 3.1. Handle Missing Values
"""

# Drop rows with missing values as they constitute a very small percentage of the dataset
df.dropna(inplace=True)
print(f"Shape after dropping missing values: {df.shape}")

"""### 3.2. Handle Duplicate Rows"""

# Drop duplicate rows
df.drop_duplicates(inplace=True)
print(f"Shape after dropping duplicates: {df.shape}")

"""### 3.3. Clean Column Names"""

# Clean column names by removing leading/trailing spaces and special characters
def clean_col_names(df):
    cols = df.columns
    new_cols = []
    for col in cols:
        new_col = col.strip()  # Remove leading/trailing spaces
        new_col = new_col.replace(' ', '_').replace('/', '_').replace('.', '').replace('-', '_') # Replace spaces, /, ., - with underscores
        new_cols.append(new_col)
    df.columns = new_cols
    return df

df = clean_col_names(df)
print("Cleaned column names:")
print(df.columns.tolist()[:10]) # Display first 10 cleaned column names

"""### 3.4. Feature Engineering (Optional Example)"""

# Example: Create a new feature (e.g., 'Packet_Rate')
# This is a placeholder; actual feature engineering would depend on domain knowledge.
df['Packet_Rate'] = df['Flow_Packets_s'] / (df['Flow_Duration'] + 1e-6)
print("Added 'Packet_Rate' feature.")
print(df[['Flow_Packets_s', 'Flow_Duration', 'Packet_Rate']].head())

"""## 4. Data Visualization

### 4.1. Distribution of Target Variable
"""

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='Label')
plt.title('Distribution of Target Variable (Label)')
plt.xlabel('Label')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""### 4.2. Correlation Matrix"""

# Select only numerical columns for correlation matrix
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""## 5. Model Building and Evaluation

### 5.1. Prepare Data for Modeling
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Separate features (X) and target (y)
X = df.drop("Label", axis=1)
y = df["Label"]

# Fix: Handle Infinite values often found in network datasets
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.fillna(X.max(), inplace=True)

# Encode target variable
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Identify numerical features
numerical_features = X.select_dtypes(include=np.number).columns

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42)

# Standardize numerical features
scaler = StandardScaler()
X_train[numerical_features] = scaler.fit_transform(X_train[numerical_features])
X_test[numerical_features] = scaler.transform(X_test[numerical_features])

print("Data prepared for modeling (Infinite values handled).")
print(f"X_train shape: {X_train.shape}")

"""### 5.2. Build and Train a Model (Example: RandomForestClassifier)"""

from sklearn.ensemble import RandomForestClassifier

# Initialize and train the model
# Using a small n_estimators for quick template execution
model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

print("Training the RandomForestClassifier...")
model.fit(X_train, y_train)
print("Model training complete.")

"""### 5.3. Make Predictions"""

y_pred = model.predict(X_test)
print("Predictions made on the test set.")

"""### 5.4. Evaluate the Model"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("\nAccuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
plt.title("Confusion Matrix")
plt.show()